In [1]:
import pandas as pd
import numpy as np
import csv
import xlsxwriter

df=pd.read_excel(r'fleet.xlsx')
df['o']=df['origin']
df['d']=df['destination']
df['o']=df['o'].replace({'IKA':1, 'TJR':2, 'THR':3, 'PSD':4, 'SDQ':5, 'KRJ':6, 'VNK':7 })
df['d']=df['d'].replace({'IKA':1, 'TJR':2, 'THR':3, 'PSD':4, 'SDQ':5, 'KRJ':6, 'VNK':7 })

In [3]:
df

,FlightNum,origin,destination,fleet1,real departure,departure,real arrival,arrival,duration,distance,o,d
0,1,KRJ,THR,4,00:05:00,0.003472,00:22:00,0.015278,00:17:00,34.00,6,3
1,2,IKA,KRJ,4,00:00:00,0.000000,00:25:00,0.017361,00:25:00,48.30,1,6
2,3,KRJ,SDQ,2,00:40:00,0.027778,00:57:00,0.039583,00:17:00,33.00,6,5
3,4,KRJ,PSD,2,00:35:00,0.024306,00:57:00,0.039583,00:22:00,43.50,6,4
4,5,KRJ,TJR,2,00:20:00,0.013889,00:40:00,0.027778,00:20:00,40.00,6,2
5,6,KRJ,VNK,2,00:10:00,0.006944,00:30:00,0.020833,00:20:00,38.90,6,7
6,7,IKA,PSD,4,00:05:00,0.003472,00:30:00,0.020833,00:25:00,50.00,1,4
7,8,IKA,TJR,4,00:10:00,0.006944,00:36:00,0.025000,00:26:00,52.00,1,2
8,9,IKA,THR,4,00:35:00,0.024306,00:54:00,0.037500,00:19:00,36.40,1,3
9,10,IKA,VNK,4,00:25:00,0.017361,00:48:00,0.033333,00:23:00,45.50,1,7
10,11,IKA,SDQ,2,00:30:00,0.020833,00:50:00,0.034722,00:20:00,40.00,1,5
11,12,KRJ,IKA,4,00:25:00,0.017361,00:50:00,0.034722,00:25:00,48.30,6,1
12,13,THR,KRJ,4,00:00:00,0.000000,00:17:00,0.011806,00:17:00,34.00,3,6
13,14,THR,IKA,4,00:05:00,0.003472,00:24:00,0.016667,00:19:00,36.40,3,1
14,15,PSD,KRJ,2,00:25:00,0.017361,00:47:00,0.032639,00:22:00,43.50,4,6
15,16,PSD,IKA,2,00:30:00,0.020833,00:55:00,0.038194,00:25:00,50.00,4,1
16,17,TJR,KRJ,2,00:20:00,0.013889,00:40:00,0.027778,00:20:00,40.00,2,6
17,18,TJR,IKA,4,00:15:00,0.010417,00:41:00,0.028472,00:26:00,52.00,2,1
18,19,SDQ,KRJ,2,00:00:00,0.000000,00:17:00,0.011806,00:17:00,33.00,5,6
19,20,SDQ,IKA,4,00:10:00,0.006944,00:30:00,0.020833,00:20:00,40.00,5,1
20,21,VNK,KRJ,2,00:15:00,0.010417,00:35:00,0.024306,00:20:00,38.90,7,6
21,22,VNK,IKA,4,00:30:00,0.020833,00:53:00,0.036806,00:23:00,45.50,7,1
22,23,THR,PSD,2,00:45:00,0.031250,00:53:00,0.036806,00:08:00,14.70,3,4
23,24,PSD,THR,2,00:00:00,0.000000,00:08:00,0.005556,00:08:00,14.70,4,3
24,25,THR,TJR,2,00:20:00,0.013889,00:28:00,0.019444,00:08:00,15.00,3,2
25,26,TJR,THR,2,00:05:00,0.003472,00:13:00,0.009028,00:08:00,15.00,2,3
26,27,THR,SDQ,2,00:10:00,0.006944,00:12:00,0.008333,00:02:00,3.80,3,5
27,28,SDQ,THR,2,00:35:00,0.024306,00:37:00,0.025694,00:02:00,3.80,5,3
28,29,THR,VNK,2,00:25:00,0.017361,00:30:00,0.020833,00:05:00,9.60,3,7
29,30,VNK,THR,2,00:20:00,0.013889,00:25:00,0.017361,00:05:00,9.60,7,3
30,31,PSD,TJR,4,00:10:00,0.006944,00:13:00,0.009028,00:03:00,4.80,4,2
31,32,TJR,PSD,2,00:00:00,0.000000,00:03:00,0.002083,00:03:00,4.80,2,4
32,33,PSD,SDQ,2,00:15:00,0.010417,00:22:00,0.015278,00:07:00,12.60,4,5
33,34,SDQ,PSD,2,00:20:00,0.013889,00:27:00,0.018750,00:07:00,12.60,5,4
34,35,PSD,VNK,2,00:05:00,0.003472,00:08:00,0.005556,00:03:00,5.30,4,7
35,36,VNK,PSD,2,00:10:00,0.006944,00:13:00,0.009028,00:03:00,5.30,7,4
36,37,SDQ,TJR,2,00:05:00,0.003472,00:11:00,0.007639,00:06:00,11.80,5,2
37,38,TJR,SDQ,2,00:30:00,0.020833,00:36:00,0.025000,00:06:00,11.80,2,5
38,39,TJR,VNK,4,00:10:00,0.006944,00:13:00,0.009028,00:03:00,5.80,2,7
39,40,VNK,TJR,2,00:00:00,0.000000,00:03:00,0.002083,00:03:00,5.80,7,2
40,41,SDQ,VNK,2,00:30:00,0.020833,00:34:00,0.023611,00:04:00,7.25,5,7
41,42,VNK,SDQ,4,00:05:00,0.003472,00:09:00,0.006250,00:04:00,7.25,7,5

In [13]:
#hourly cycle loop 
#range(number of flight)


a=[]
for i in range(42):    #range(number of flight) 15 min 
    if df['fleet1'].loc[i]==4:  #name aircarft
        b=np.zeros(3)
        c=df['FlightNum'].loc[i]
        b[0]=(c)
        a.append(b)
        
    else:
        continue
            
    for i1 in range(42):                                             #0.01=10 min bitween arivall andeparture
        if df['d'].loc[i]==df['o'].loc[i1]  and df['fleet1'].loc[i1]==4 and ((df['arrival'].loc[i]+0.007) <= df['departure'].loc[i1]):
            b=np.zeros(3)
            c=df['FlightNum'].loc[i]
            d=df['FlightNum'].loc[i1]
            b[0]=(c)
            b[1]=(d)

            a.append(b)
           
        else:
            continue
        for i2 in range(42):
            if df['d'].loc[i1]==df['o'].loc[i2] and df['fleet1'].loc[i2]==4 and ((df['arrival'].loc[i1]+0.007) <= df['departure'].loc[i2]):
                b=np.zeros(3)
                c=df['FlightNum'].loc[i]
                d=df['FlightNum'].loc[i1]
                e=df['FlightNum'].loc[i2]
                b[0]=(c)
                b[1]=(d)
                b[2]=(e)
                a.append(b)
            
            else:
                continue
            
            
                    
                    
a

[array([1., 0., 0.]),
 array([2., 0., 0.]),
 array([7., 0., 0.]),
 array([8., 0., 0.]),
 array([9., 0., 0.]),
 array([10.,  0.,  0.]),
 array([12.,  0.,  0.]),
 array([13.,  0.,  0.]),
 array([14.,  0.,  0.]),
 array([14.,  9.,  0.]),
 array([18.,  0.,  0.]),
 array([20.,  0.,  0.]),
 array([22.,  0.,  0.]),
 array([31.,  0.,  0.]),
 array([39.,  0.,  0.]),
 array([39., 22.,  0.]),
 array([42.,  0.,  0.])]

In [14]:
len(a)

17

In [15]:
#each combination how many flight have
b=np.zeros(len(a))
for i in range(len(a)):
    for j in range(3):
        if a[i][j]>0:
            b[i]=b[i]+1
for i in range(len(a)):
    b[i]=b[i]-1

In [16]:
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.])

In [17]:
c=[]
for i in range(len(a)):
    c0=a[i][0] 
    f= int(b[i])
    c1=a[i][f]
    for i2 in range(len(a)):
        c2=a[i2][0]
        f=int(b[i2])
        c3=a[i2][f]
        if (df['d'].loc[(c1-1)]==df['o'].loc[(c2-1)]) and (df['d'].loc[(c3-1)]==df['o'].loc[(c0-1)]) :
            if (df['d'].loc[(c3-1)]==1 or df['d'].loc[(c3-1)]==2)  or (df['d'].loc[(c1-1)]==1 or df['d'].loc[(c1-1)]==2) :
                d=np.insert(a[i],3,a[i2])
                c.append(d)
            else:
                continue
            


len(c)

10

In [19]:
c=[]
for i in range(len(a)):
    c0=a[i][0] 
    f= int(b[i])
    c1=a[i][f]
    for i2 in range(len(a)):
        c2=a[i2][0]
        f=int(b[i2])
        c3=a[i2][f]
        for i3 in range(len(a)):
            c4=a[i3][0]
            f=int(b[i3])
            c5=a[i3][f]
            if ((df['d'].loc[(c1-1)]==df['o'].loc[(c2-1)]) and (df['d'].loc[(c3-1)]==df['o'].loc[(c4-1)]) and (df['d'].loc[(c5-1)]==df['o'].loc[(c0-1)])):
                if (df['d'].loc[(c5-1)]==1 or df['d'].loc[(c5-1)]==2) or (df['d'].loc[(c3-1)]==1 or df['d'].loc[(c3-1)]==2) or (df['d'].loc[(c1-1)]==1 or df['d'].loc[(c1-1)]==2):
                    d=np.insert(a[i],3,a[i2])
                    d=np.insert(d,6,a[i3])
                    c.append(d)
                else:
                    continue
            


len(c)

21

In [21]:
#make 3 shift in cycle 15 min stay in hub charger 

c=[]
for i in range(len(a)):
    c0=a[i][0] 
    f= int(b[i])
    c1=a[i][f]
    for i2 in range(len(a)):
        c2=a[i2][0]
        f=int(b[i2])
        c3=a[i2][f]
        for i3 in range(len(a)):
            c4=a[i3][0]
            f=int(b[i3])
            c5=a[i3][f]
            for i4 in range(len(a)):
                c6=a[i4][0]
                f=int(b[i4])
                c7=a[i4][f]
                if ((df['d'].loc[(c1-1)]==df['o'].loc[(c2-1)]) and (df['d'].loc[(c3-1)]==df['o'].loc[(c4-1)]) and (df['d'].loc[(c5-1)]==df['o'].loc[(c6-1)]) and (df['d'].loc[(c7-1)]==df['o'].loc[(c0-1)])):
                    if (df['d'].loc[(c7-1)]==1 or df['d'].loc[(c7-1)]==2) or (df['d'].loc[(c5-1)]==1 or df['d'].loc[(c5-1)]==2) or (df['d'].loc[(c3-1)]==1 or df['d'].loc[(c3-1)]==2) or (df['d'].loc[(c1-1)]==1 or df['d'].loc[(c1-1)]==2):
                        d=np.insert(a[i],3,a[i2])
                        d=np.insert(d,6,a[i3])
                        d=np.insert(d,9,a[i4])
                        c.append(d)
                    else:
                        continue
            


len(c)

78

In [22]:
c

[array([ 1.,  0.,  0., 13.,  0.,  0., 12.,  0.,  0.,  2.,  0.,  0.]),
 array([ 1.,  0.,  0., 14.,  0.,  0.,  9.,  0.,  0., 13.,  0.,  0.]),
 array([ 1.,  0.,  0., 14.,  9.,  0., 14.,  0.,  0.,  2.,  0.,  0.]),
 array([ 2.,  0.,  0.,  1.,  0.,  0., 13.,  0.,  0., 12.,  0.,  0.]),
 array([ 2.,  0.,  0.,  1.,  0.,  0., 14.,  9.,  0., 14.,  0.,  0.]),
 array([ 2.,  0.,  0., 12.,  0.,  0.,  2.,  0.,  0., 12.,  0.,  0.]),
 array([ 2.,  0.,  0., 12.,  0.,  0.,  8.,  0.,  0., 18.,  0.,  0.]),
 array([ 2.,  0.,  0., 12.,  0.,  0.,  8.,  0.,  0., 39., 22.,  0.]),
 array([ 2.,  0.,  0., 12.,  0.,  0.,  9.,  0.,  0., 14.,  0.,  0.]),
 array([ 2.,  0.,  0., 12.,  0.,  0., 10.,  0.,  0., 22.,  0.,  0.]),
 array([ 7.,  0.,  0., 31.,  0.,  0., 39.,  0.,  0., 22.,  0.,  0.]),
 array([ 8.,  0.,  0., 18.,  0.,  0.,  2.,  0.,  0., 12.,  0.,  0.]),
 array([ 8.,  0.,  0., 18.,  0.,  0.,  8.,  0.,  0., 18.,  0.,  0.]),
 array([ 8.,  0.,  0., 18.,  0.,  0.,  8.,  0.,  0., 39., 22.,  0.]),
 array([ 8.,  0.,  0., 18.,  0.,  0.,  9.,  0.,  0., 14.,  0.,  0.]),
 array([ 8.,  0.,  0., 18.,  0.,  0., 10.,  0.,  0., 22.,  0.,  0.]),
 array([ 8.,  0.,  0., 39.,  0.,  0., 42.,  0.,  0., 20.,  0.,  0.]),
 array([ 8.,  0.,  0., 39., 22.,  0.,  2.,  0.,  0., 12.,  0.,  0.]),
 array([ 8.,  0.,  0., 39., 22.,  0.,  8.,  0.,  0., 18.,  0.,  0.]),
 array([ 8.,  0.,  0., 39., 22.,  0.,  8.,  0.,  0., 39., 22.,  0.]),
 array([ 8.,  0.,  0., 39., 22.,  0.,  9.,  0.,  0., 14.,  0.,  0.]),
 array([ 8.,  0.,  0., 39., 22.,  0., 10.,  0.,  0., 22.,  0.,  0.]),
 array([ 9.,  0.,  0., 13.,  0.,  0.,  1.,  0.,  0., 14.,  0.,  0.]),
 array([ 9.,  0.,  0., 14.,  0.,  0.,  2.,  0.,  0., 12.,  0.,  0.]),
 array([ 9.,  0.,  0., 14.,  0.,  0.,  8.,  0.,  0., 18.,  0.,  0.]),
 array([ 9.,  0.,  0., 14.,  0.,  0.,  8.,  0.,  0., 39., 22.,  0.]),
 array([ 9.,  0.,  0., 14.,  0.,  0.,  9.,  0.,  0., 14.,  0.,  0.]),
 array([ 9.,  0.,  0., 14.,  0.,  0., 10.,  0.,  0., 22.,  0.,  0.]),
 array([ 9.,  0.,  0., 14.,  9.,  0., 13.,  0.,  0., 12.,  0.,  0.]),
 array([ 9.,  0.,  0., 14.,  9.,  0., 14.,  9.,  0., 14.,  0.,  0.]),
 array([10.,  0.,  0., 22.,  0.,  0.,  2.,  0.,  0., 12.,  0.,  0.]),
 array([10.,  0.,  0., 22.,  0.,  0.,  8.,  0.,  0., 18.,  0.,  0.]),
 array([10.,  0.,  0., 22.,  0.,  0.,  8.,  0.,  0., 39., 22.,  0.]),
 array([10.,  0.,  0., 22.,  0.,  0.,  9.,  0.,  0., 14.,  0.,  0.]),
 array([10.,  0.,  0., 22.,  0.,  0., 10.,  0.,  0., 22.,  0.,  0.]),
 array([12.,  0.,  0.,  2.,  0.,  0.,  1.,  0.,  0., 13.,  0.,  0.]),
 array([12.,  0.,  0.,  2.,  0.,  0., 12.,  0.,  0.,  2.,  0.,  0.]),
 array([12.,  0.,  0.,  8.,  0.,  0., 18.,  0.,  0.,  2.,  0.,  0.]),
 array([12.,  0.,  0.,  8.,  0.,  0., 39., 22.,  0.,  2.,  0.,  0.]),
 array([12.,  0.,  0.,  9.,  0.,  0., 14.,  0.,  0.,  2.,  0.,  0.]),
 array([12.,  0.,  0.,  9.,  0.,  0., 14.,  9.,  0., 13.,  0.,  0.]),
 array([12.,  0.,  0., 10.,  0.,  0., 22.,  0.,  0.,  2.,  0.,  0.]),
 array([13.,  0.,  0.,  1.,  0.,  0., 14.,  0.,  0.,  9.,  0.,  0.]),
 array([13.,  0.,  0., 12.,  0.,  0.,  2.,  0.,  0.,  1.,  0.,  0.]),
 array([13.,  0.,  0., 12.,  0.,  0.,  9.,  0.,  0., 14.,  9.,  0.]),
 array([14.,  0.,  0.,  2.,  0.,  0.,  1.,  0.,  0., 14.,  9.,  0.]),
 array([14.,  0.,  0.,  2.,  0.,  0., 12.,  0.,  0.,  9.,  0.,  0.]),
 array([14.,  0.,  0.,  8.,  0.,  0., 18.,  0.,  0.,  9.,  0.,  0.]),
 array([14.,  0.,  0.,  8.,  0.,  0., 39., 22.,  0.,  9.,  0.,  0.]),
 array([14.,  0.,  0.,  9.,  0.,  0., 13.,  0.,  0.,  1.,  0.,  0.]),
 array([14.,  0.,  0.,  9.,  0.,  0., 14.,  0.,  0.,  9.,  0.,  0.]),
 array([14.,  0.,  0.,  9.,  0.,  0., 14.,  9.,  0., 14.,  9.,  0.]),
 array([14.,  0.,  0., 10.,  0.,  0., 22.,  0.,  0.,  9.,  0.,  0.]),
 array([14.,  9.,  0., 13.,  0.,  0., 12.,  0.,  0.,  9.,  0.,  0.]),
 array([14.,  9.,  0., 14.,  0.,  0.,  2.,  0.,  0.,  1.,  0.,  0.]),
 array([14.,  9.,  0., 14.,  0.,  0.,  9.,  0.,  0., 14.,  9.,  0.]),
 array([14.,  9.,  0., 14.,  9.,  0., 14.,  0.,  0.,  9.,  0.,  0.]),
 array([18.,  0.,  0.,  2.,  0.,  0., 12.,  0.,  0.,  8.,  0.,  0.]),
 array([18.,  0.,  0.,  8.,  0.,  0., 18.,  0.,  0.,  8.,  0.,  0.]),
 array([18.,  0.,  0.,  8.,  0.,  0., 39., 22.,  0.,  8.,  0.,  0.]),
 array([18.,  0.,  0.,  9.,  0.,  0., 14.,  0.,  0.,  8.,  0.,  0.]),
 array([18.,  0.,  0., 10.,  0.,  0., 22.,  0.,  0.,  8.,  0.,  0.]),
 array([20.,  0.,  0.,  8.,  0.,  0., 39.,  0.,  0., 42.,  0.,  0.]),
 array([22.,  0.,  0.,  2.,  0.,  0., 12.,  0.,  0., 10.,  0.,  0.]),
 array([22.,  0.,  0.,  7.,  0.,  0., 31.,  0.,  0., 39.,  0.,  0.]),
 array([22.,  0.,  0.,  8.,  0.,  0., 18.,  0.,  0., 10.,  0.,  0.]),
 array([22.,  0.,  0.,  8.,  0.,  0., 39., 22.,  0., 10.,  0.,  0.]),
 array([22.,  0.,  0.,  9.,  0.,  0., 14.,  0.,  0., 10.,  0.,  0.]),
 array([22.,  0.,  0., 10.,  0.,  0., 22.,  0.,  0., 10.,  0.,  0.]),
 array([31.,  0.,  0., 39.,  0.,  0., 22.,  0.,  0.,  7.,  0.,  0.]),
 array([39.,  0.,  0., 22.,  0.,  0.,  7.,  0.,  0., 31.,  0.,  0.]),
 array([39.,  0.,  0., 42.,  0.,  0., 20.,  0.,  0.,  8.,  0.,  0.]),
 array([39., 22.,  0.,  2.,  0.,  0., 12.,  0.,  0.,  8.,  0.,  0.]),
 array([39., 22.,  0.,  8.,  0.,  0., 18.,  0.,  0.,  8.,  0.,  0.]),
 array([39., 22.,  0.,  8.,  0.,  0., 39., 22.,  0.,  8.,  0.,  0.]),
 array([39., 22.,  0.,  9.,  0.,  0., 14.,  0.,  0.,  8.,  0.,  0.]),
 array([39., 22.,  0., 10.,  0.,  0., 22.,  0.,  0.,  8.,  0.,  0.]),
 array([42.,  0.,  0., 20.,  0.,  0.,  8.,  0.,  0., 39.,  0.,  0.])]

In [23]:
file = open('cycle_s4_2f_4h.csv', 'w+', newline ='') 
with file:     
    write = csv.writer(file) 
    write.writerows(c)